# Generated by Django 5.1.6 on 2025-04-03 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_artisan_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
