# Generated by Django 5.1.6 on 2025-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_artisan_product_artisan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='artisan',
            name='artisan_type',
            field=models.CharField(choices=[('textile_weaver', 'Textile Weaver'), ('potter', 'Potter'), ('woodworker', 'Woodworker'), ('metalsmith', 'Metalsmith'), ('jewelry_maker', 'Jewelry Maker'), ('basket_weaver', 'Basket Weaver'), ('leather_worker', 'Leather Worker'), ('paper_maker', 'Paper Maker'), ('glass_blower', 'Glass Blower'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisan',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisan',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
