# Generated by Django 5.1.6 on 2025-03-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', 'fix_admin_log_fk'),
    ]

    operations = [
    ]
