# Generated by Django 5.1.6 on 2025-04-02 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artisans', to=settings.AUTH_USER_MODEL),
        ),
    ]
